sudo: false
language: python

python:
    - "3.5"

env:
    - TOX_ENV=flake8
    - TOX_ENV=py27-django18-wagtail15
    - TOX_ENV=py33-django18-wagtail15
    - TOX_ENV=py34-django18-wagtail15
    - TOX_ENV=py35-django18-wagtail15
    - TOX_ENV=py27-django18-wagtail16
    - TOX_ENV=py33-django18-wagtail16
    - TOX_ENV=py34-django18-wagtail16
    - TOX_ENV=py35-django18-wagtail16
    - TOX_ENV=py27-django18-wagtail17
    - TOX_ENV=py33-django18-wagtail17
    - TOX_ENV=py34-django18-wagtail17
    - TOX_ENV=py35-django18-wagtail17
    - TOX_ENV=py27-django19-wagtail15
    - TOX_ENV=py34-django19-wagtail15
    - TOX_ENV=py35-django19-wagtail15
    - TOX_ENV=py27-django19-wagtail16
    - TOX_ENV=py34-django19-wagtail16
    - TOX_ENV=py35-django19-wagtail16
    - TOX_ENV=py27-django19-wagtail17
    - TOX_ENV=py34-django19-wagtail17
    - TOX_ENV=py35-django19-wagtail17
    - TOX_ENV=py27-django110-wagtail16
    - TOX_ENV=py34-django110-wagtail16
    - TOX_ENV=py35-django110-wagtail16
    - TOX_ENV=py27-django110-wagtail17
    - TOX_ENV=py34-django110-wagtail17
    - TOX_ENV=py35-django110-wagtail17

matrix:
    fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
